package fio

var ElastoDyn = NewFile("ElastoDyn", []Field{
	{Type: Heading, Desc: "ElastoDyn Input File"},
	{Name: "Title", Type: Title},
	{Type: Heading, Desc: "Simulation Control"},
	{Name: "Echo", Type: Bool, Desc: `Echo input data to <RootName>.ech`, Unit: "flag"},
	{Name: "Method", Type: Int, Desc: `Integration method: {1: RK4, 2: AB4, or 3: ABM4}`},
	{Name: "DT", Type: FloatDefault, Desc: `Integration time step`, Unit: "s"},
	{Type: Heading, Desc: `Degrees of Freedom`},
	{Name: "FlapDOF1", Type: Bool, Desc: `First flapwise blade mode DOF`, Unit: "flag"},
	{Name: "FlapDOF2", Type: Bool, Desc: `Second flapwise blade mode DOF`, Unit: "flag"},
	{Name: "EdgeDOF", Type: Bool, Desc: `First edgewise blade mode DOF`, Unit: "flag"},
	{Name: "TeetDOF", Type: Bool, Desc: `Rotor-teeter DOF (flag) [unused for 3 blades]`, Unit: "flag"},
	{Name: "DrTrDOF", Type: Bool, Desc: `Drivetrain rotational-flexibility DOF`, Unit: "flag"},
	{Name: "GenDOF", Type: Bool, Desc: `Generator DOF`, Unit: "flag"},
	{Name: "YawDOF", Type: Bool, Desc: `Yaw DOF`, Unit: "flag"},
	{Name: "TwFADOF1", Type: Bool, Desc: `First fore-aft tower bending-mode DOF`, Unit: "flag"},
	{Name: "TwFADOF2", Type: Bool, Desc: `Second fore-aft tower bending-mode DOF`, Unit: "flag"},
	{Name: "TwSSDOF1", Type: Bool, Desc: `First side-to-side tower bending-mode DOF`, Unit: "flag"},
	{Name: "TwSSDOF2", Type: Bool, Desc: `Second side-to-side tower bending-mode DOF`, Unit: "flag"},
	{Name: "PtfmSgDOF", Type: Bool, Desc: `Platform horizontal surge translation DOF`, Unit: "flag"},
	{Name: "PtfmSwDOF", Type: Bool, Desc: `Platform horizontal sway translation DOF`, Unit: "flag"},
	{Name: "PtfmHvDOF", Type: Bool, Desc: `Platform vertical heave translation DOF`, Unit: "flag"},
	{Name: "PtfmRDOF", Type: Bool, Desc: `Platform roll tilt rotation DOF`, Unit: "flag"},
	{Name: "PtfmPDOF", Type: Bool, Desc: `Platform pitch tilt rotation DOF`, Unit: "flag"},
	{Name: "PtfmYDOF", Type: Bool, Desc: `Platform yaw rotation DOF`, Unit: "flag"},
	{Type: Heading, Desc: `Initial Conditions`},
	{Name: "OoPDefl", Type: Float, Desc: `Initial out-of-plane blade-tip displacement`, Unit: "meters"},
	{Name: "IPDefl", Type: Float, Desc: `Initial in-plane blade-tip deflection`, Unit: "meters"},
	{Name: "BlPitch(1)", Type: Float, Desc: `Blade 1 initial pitch`, Unit: "degrees"},
	{Name: "BlPitch(2)", Type: Float, Desc: `Blade 2 initial pitch`, Unit: "degrees"},
	{Name: "BlPitch(3)", Type: Float, Desc: `Blade 3 initial pitch [unused for 2 blades]`, Unit: "degrees"},
	{Name: "TeetDefl", Type: Float, Desc: `Initial or fixed teeter angle [unused for 3 blades]`, Unit: "degrees"},
	{Name: "Azimuth", Type: Float, Desc: `Initial azimuth angle for blade 1`, Unit: "degrees"},
	{Name: "RotSpeed", Type: Float, Desc: `Initial or fixed rotor speed`, Unit: "rpm"},
	{Name: "NacYaw", Type: Float, Desc: `Initial or fixed nacelle-yaw angle`, Unit: "degrees"},
	{Name: "TTDspFA", Type: Float, Desc: `Initial fore-aft tower-top displacement`, Unit: "meters"},
	{Name: "TTDspSS", Type: Float, Desc: `Initial side-to-side tower-top displacement`, Unit: "meters"},
	{Name: "PtfmSurge", Type: Float, Desc: `Initial or fixed horizontal surge translational displacement of platform`, Unit: "meters"},
	{Name: "PtfmSway", Type: Float, Desc: `Initial or fixed horizontal sway translational displacement of platform`, Unit: "meters"},
	{Name: "PtfmHeave", Type: Float, Desc: `Initial or fixed vertical heave translational displacement of platform`, Unit: "meters"},
	{Name: "PtfmRoll", Type: Float, Desc: `Initial or fixed roll tilt rotational displacement of platform`, Unit: "degrees"},
	{Name: "PtfmPitch", Type: Float, Desc: `Initial or fixed pitch tilt rotational displacement of platform`, Unit: "degrees"},
	{Name: "PtfmYaw", Type: Float, Desc: `Initial or fixed yaw rotational displacement of platform`, Unit: "degrees"},
	{Type: Heading, Desc: `Turbine Configuration`},
	{Name: "NumBl", Type: Int, Desc: `Number of blades`},
	{Name: "TipRad", Type: Float, Desc: `The distance from the rotor apex to the blade tip`, Unit: "meters"},
	{Name: "HubRad", Type: Float, Desc: `The distance from the rotor apex to the blade root`, Unit: "meters"},
	{Name: "PreCone(1)", Type: Float, Desc: `Blade 1 cone angle`, Unit: "degrees"},
	{Name: "PreCone(2)", Type: Float, Desc: `Blade 2 cone angle`, Unit: "degrees"},
	{Name: "PreCone(3)", Type: Float, Desc: `Blade 3 cone angle [unused for 2 blades]`, Unit: "degrees"},
	{Name: "HubCM", Type: Float, Desc: `Distance from rotor apex to hub mass [positive downwind]`, Unit: "meters"},
	{Name: "UndSling", Type: Float, Desc: `Undersling length [distance from teeter pin to the rotor apex] (meters) [unused for 3 blades]`},
	{Name: "Delta3", Type: Float, Desc: `Delta-3 angle for teetering rotors [unused for 3 blades]`, Unit: "degrees"},
	{Name: "AzimB1Up", Type: Float, Desc: `Azimuth value to use for I/O when blade 1 points up`, Unit: "degrees"},
	{Name: "OverHang", Type: Float, Desc: `Distance from yaw axis to rotor apex [3 blades] or teeter pin [2 blades]`, Unit: "meters"},
	{Name: "ShftGagL", Type: Float, Desc: `Distance from rotor apex [3 blades] or teeter pin [2 blades] to shaft strain gages [positive for upwind rotors]`, Unit: "meters"},
	{Name: "ShftTilt", Type: Float, Desc: `Rotor shaft tilt angle`, Unit: "degrees"},
	{Name: "NacCMxn", Type: Float, Desc: `Downwind distance from the tower-top to the nacelle CM`, Unit: "meters"},
	{Name: "NacCMyn", Type: Float, Desc: `Lateral  distance from the tower-top to the nacelle CM`, Unit: "meters"},
	{Name: "NacCMzn", Type: Float, Desc: `Vertical distance from the tower-top to the nacelle CM`, Unit: "meters"},
	{Name: "NcIMUxn", Type: Float, Desc: `Downwind distance from the tower-top to the nacelle IMU`, Unit: "meters"},
	{Name: "NcIMUyn", Type: Float, Desc: `Lateral  distance from the tower-top to the nacelle IMU`, Unit: "meters"},
	{Name: "NcIMUzn", Type: Float, Desc: `Vertical distance from the tower-top to the nacelle IMU`, Unit: "meters"},
	{Name: "Twr2Shft", Type: Float, Desc: `Vertical distance from the tower-top to the rotor shaft`, Unit: "meters"},
	{Name: "TowerHt", Type: Float, Desc: `Height of tower above ground level [onshore], MSL [offshore], or seabed [MHK]`, Unit: "meters"},
	{Name: "TowerBsHt", Type: Float, Desc: `Height of tower base above ground level [onshore], MSL [offshore], or seabed [MHK]`, Unit: "meters"},
	{Name: "PtfmCMxt", Type: Float, Desc: `Downwind distance from the ground level [onshore], MSL [offshore], or seabed [MHK] to the platform CM`, Unit: "meters"},
	{Name: "PtfmCMyt", Type: Float, Desc: `Lateral distance from the ground level [onshore], MSL [offshore], or seabed [MHK] to the platform CM`, Unit: "meters"},
	{Name: "PtfmCMzt", Type: Float, Desc: `Vertical distance from the ground level [onshore], MSL [offshore], or seabed [MHK] to the platform CM`, Unit: "meters"},
	{Name: "PtfmRefzt", Type: Float, Desc: `Vertical distance from the ground level [onshore], MSL [offshore], or seabed [MHK] to the platform reference point`, Unit: "meters"},
	{Type: Heading, Desc: `Mass and Inertia`},
	{Name: "TipMass(1)", Type: Float, Desc: `Tip-brake mass, blade 1`, Unit: "kg"},
	{Name: "TipMass(2)", Type: Float, Desc: `Tip-brake mass, blade 2`, Unit: "kg"},
	{Name: "TipMass(3)", Type: Float, Desc: `Tip-brake mass, blade 3 [unused for 2 blades]`, Unit: "kg"},
	{Name: "HubMass", Type: Float, Desc: `Hub mass`, Unit: "kg"},
	{Name: "HubIner", Type: Float, Desc: `Hub inertia about rotor axis [3 blades] or teeter axis [2 blades]`, Unit: "kg m^2"},
	{Name: "GenIner", Type: Float, Desc: `Generator inertia about HSS`, Unit: "kg m^2"},
	{Name: "NacMass", Type: Float, Desc: `Nacelle mass`, Unit: "kg"},
	{Name: "NacYIner", Type: Float, Desc: `Nacelle inertia about yaw axis`, Unit: "kg m^2"},
	{Name: "YawBrMass", Type: Float, Desc: `Yaw bearing mass`, Unit: "kg"},
	{Name: "PtfmMass", Type: Float, Desc: `Platform mass`, Unit: "kg"},
	{Name: "PtfmRIner", Type: Float, Desc: `Platform inertia for roll tilt rotation about the platform CM`, Unit: "kg m^2"},
	{Name: "PtfmPIner", Type: Float, Desc: `Platform inertia for pitch tilt rotation about the platform CM`, Unit: "kg m^2"},
	{Name: "PtfmYIner", Type: Float, Desc: `Platform inertia for yaw rotation about the platform CM`, Unit: "kg m^2"},
	{Type: Heading, Desc: `Blade`},
	{Name: "BldNodes", Type: Int, Desc: `Number of blade nodes (per blade) used for analysis`},
	{Name: "BldFile(1)", Type: Path, Desc: `Name of file containing properties for blade 1`, Unit: "quoted string",
		PathFileType: "ElastoDynBlade"},
	{Name: "BldFile(2)", Type: Path, Desc: `Name of file containing properties for blade 2`, Unit: "quoted string",
		PathFileType: "ElastoDynBlade"},
	{Name: "BldFile(3)", Type: Path, Desc: `Name of file containing properties for blade 3 [unused for 2 blades]`, Unit: "quoted string",
		PathFileType: "ElastoDynBlade"},
	{Type: Heading, Desc: `Rotor-Teeter`},
	{Name: "TeetMod", Type: Int, Desc: `Rotor-teeter spring/damper model {0: none, 1: standard, 2: user-defined from routine UserTeet} [unused for 3 blades]`, Unit: "switch"},
	{Name: "TeetDmpP", Type: Float, Desc: `Rotor-teeter damper position [used only for 2 blades and when TeetMod=1]`, Unit: "degrees"},
	{Name: "TeetDmp", Type: Float, Desc: `Rotor-teeter damping constant [used only for 2 blades and when TeetMod=1]`, Unit: "N-m/(rad/s)"},
	{Name: "TeetCDmp", Type: Float, Desc: `Rotor-teeter rate-independent Coulomb-damping moment [used only for 2 blades and when TeetMod=1]`, Unit: "N-m"},
	{Name: "TeetSStP", Type: Float, Desc: `Rotor-teeter soft-stop position [used only for 2 blades and when TeetMod=1]`, Unit: "degrees"},
	{Name: "TeetHStP", Type: Float, Desc: `Rotor-teeter hard-stop position [used only for 2 blades and when TeetMod=1]`, Unit: "degrees"},
	{Name: "TeetSSSp", Type: Float, Desc: `Rotor-teeter soft-stop linear-spring constant [used only for 2 blades and when TeetMod=1]`, Unit: "N-m/rad"},
	{Name: "TeetHSSp", Type: Float, Desc: `Rotor-teeter hard-stop linear-spring constant [used only for 2 blades and when TeetMod=1]`, Unit: "N-m/rad"},
	{Type: Heading, Desc: `Drivetrain`},
	{Name: "GBoxEff", Type: Float, Desc: `Gearbox efficiency`, Unit: "%"},
	{Name: "GBRatio", Type: Float, Desc: `Gearbox ratio`, Unit: "-"},
	{Name: "DTTorSpr", Type: Float, Desc: `Drivetrain torsional spring`, Unit: "N-m/rad"},
	{Name: "DTTorDmp", Type: Float, Desc: `Drivetrain torsional damper`, Unit: "N-m/(rad/s)"},
	{Type: Heading, Desc: `Furling`},
	{Name: "Furling", Type: Bool, Desc: `Read in additional model properties for furling turbine [must currently be FALSE)`, Unit: "flag"},
	{Name: "FurlFile", Type: Path, Desc: `Name of file containing furling properties [unused when Furling=False]`, Unit: "quoted string",
		PathFileType: ""},
	{Type: Heading, Desc: `Tower`},
	{Name: "TwrNodes", Type: Int, Desc: `Number of tower nodes used for analysis`},
	{Name: "TwrFile", Type: Path, Desc: `Name of file containing tower properties`, Unit: "quoted string",
		PathFileType: "ElastoDynTower"},
	{Type: Heading, Desc: `Output`},
	{Name: "SumPrint", Type: Bool, Desc: `Print summary data to "<RootName>.sum"`, Unit: "flag"},
	{Name: "OutFile", Type: Int, Desc: `Switch to determine where output will be placed: {1: in module output file only; 2: in glue code output file only; 3: both} (currently unused)`},
	{Name: "TabDelim", Type: Bool, Desc: `Use tab delimiters in text tabular output file? (currently unused)`, Unit: "flag"},
	{Name: "OutFmt", Type: String, Desc: `Format used for text tabular output (except time).  Resulting field should be 10 characters. (currently unused)`, Unit: "quoted string"},
	{Name: "TStart", Type: Float, Desc: `Time to begin tabular output (currently unused)`, Unit: "s"},
	{Name: "DecFact", Type: Int, Desc: `Decimation factor for tabular output {1: output every time step} (currently unused)`},
	{Name: "NTwGages", Type: Int, Desc: `Number of tower nodes that have strain gages for output [0 to 9]`},
	{Name: "TwrGagNd", Type: Ints, Num: "NTwGages", Desc: `List of tower nodes that have strain gages [1 to TwrNodes] [unused if NTwGages=0]`},
	{Name: "NBlGages", Type: Int, Desc: `Number of blade nodes that have strain gages for output [0 to 9]`},
	{Name: "BldGagNd", Type: Ints, Num: "NBlGages", Desc: `List of blade nodes that have strain gages [1 to BldNodes] [unused if NBlGages=0]`},
	{Name: "OutList", Type: OutList, Desc: `The next line(s) contains a list of output parameters.  See OutListParameters.xlsx for a listing of available output channels`},
})
