baseURL = "/"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "ACDC"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true


# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 10

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Docs"
url = "/docs/"
weight = 2

[params]
google_analytics_id = ""
homepage_button_link = '/acdc/docs'
homepage_button_text = 'Read The Docs'
homepage_intro = 'ACDC is a tool for generating Campbell Diagrams and exploring the dynamic properties of wind turbines modeled in OpenFAST.'
homepage_image = 'images/cd_tn.png'

## You can enable to add anchor links to header elements
# enable_anchor_link = true

[params.homepage_meta_tags]
meta_description = "ACDC is an app for generating Campbell Diagrams with OpenFAST"
meta_og_title = "ACDC: Automated Campbell Diagram Code"
meta_og_type = "website"
meta_og_url = "https://openfast.github.io/acdc"
meta_og_image = "https://raw.githubusercontent.com/openfast/acdc/docs/static/images/cd_tn.png"
meta_og_description = "ACDC is an app for generating Campbell Diagrams with OpenFAST"
# meta_twitter_card = "summary"
# meta_twitter_site = "@zerostaticio"
# meta_twitter_creator = "@zerostaticio"

[params.logo]
mobile = "images/logo.png"
standard = "images/logo.png"

[params.footer]
copyright_text = 'ACDC by <a href="https://www.nrel.gov/">NREL</a>'
