package schema

var BeamDyn = RegisterSchemas("BeamDyn", []Schema{
	{Type: Header, Desc: "BeamDyn Input File"},
	{Name: "Title", Type: Title},
	{Type: Header, Desc: "Simulation Control"},
	{Name: "Echo", Type: Bool, Desc: `Echo input data to "<RootName>.ech"?`, Unit: "flag"},
	{Name: "QuasiStaticInit", Type: Bool, Desc: `Use quasi-static pre-conditioning with centripetal accelerations in initialization? [dynamic solve only]`, Unit: "flag"},
	{Name: "rhoinf", Type: Float, Desc: `Numerical damping parameter for generalized-alpha integrator`},
	{Name: "quadrature", Type: Int, Desc: `Quadrature method: 1=Gaussian; 2=Trapezoidal`, Unit: "switch"},
	{Name: "refine", Type: IntDefault, Desc: `Refinement factor for trapezoidal quadrature [DEFAULT = 1; used only when quadrature=2]`},
	{Name: "n_fact", Type: IntDefault, Desc: `Factorization frequency for the Jacobian in N-R iteration [DEFAULT = 5]`},
	{Name: "DTBeam", Type: FloatDefault, Desc: `Time step size`, Unit: "s"},
	{Name: "load_retries", Type: IntDefault, Desc: `Number of factored load retries before quitting the simulation [DEFAULT = 20]`},
	{Name: "NRMax", Type: IntDefault, Desc: `Max number of iterations in Newton-Raphson algorithm [DEFAULT = 10]`},
	{Name: "stop_tol", Type: FloatDefault, Desc: `Tolerance for stopping criterion [DEFAULT = 1E-5]`},
	{Name: "tngt_stf_fd", Type: BoolDefault, Desc: `Use finite differenced tangent stiffness matrix?`, Unit: "flag"},
	{Name: "tngt_stf_comp", Type: BoolDefault, Desc: `Compare analytical finite differenced tangent stiffness matrix?`, Unit: "flag"},
	{Name: "tngt_stf_pert", Type: FloatDefault, Desc: `Perturbation size for finite differencing [DEFAULT = 1E-6]`},
	{Name: "tngt_stf_difftol", Type: FloatDefault, Desc: `Maximum allowable relative difference between analytical and fd tangent stiffness; [DEFAULT = 0.1]`},
	{Name: "RotStates", Type: Bool, Desc: `Orient states in the rotating frame during linearization? [used only when linearizing] `, Unit: "flag"},
	{Type: Header, Desc: `Geometry Parameter`},
	{Name: "member_total", Type: Int, Desc: `Total number of members`},
	{Name: "kp_total", Type: Int, Desc: `Total number of key points [must be at least 3]`},
	{Name: "KPMember", Type: Table, NumVar: "member_total",
		TableHeaderSize: 0,
		TableColumns: []Column{
			{Name: "Member", Type: Int, Unit: "-"},
			{Name: "NumKP", Type: Int, Unit: "-"},
		}},
	{Name: "KPData", Type: Table, NumVar: "kp_total",
		TableHeaderSize: 2,
		TableColumns: []Column{
			{Name: "kp_xr", Type: Float, Unit: "m"},
			{Name: "kp_yr", Type: Float, Unit: "m"},
			{Name: "kp_zr", Type: Float, Unit: "m"},
			{Name: "initial_twist", Type: Float, Unit: "deg"},
		}},
	{Type: Header, Desc: `Mesh Parameter`},
	{Name: "order_elem", Type: Int, Desc: `Order of interpolation (basis) function`},
	{Type: Header, Desc: `Material Parameter`},
	{Name: "BldFile", Type: File, FileType: "BeamDynBlade", Desc: `Name of file containing properties for blade`, Unit: "quoted string"},
	{Type: Header, Desc: `Pitch Actuator Parameters`},
	{Name: "UsePitchAct", Type: Bool, Desc: `Whether a pitch actuator should be used`, Unit: "flag"},
	{Name: "PitchJ", Type: Float, Desc: `Pitch actuator inertia [used only when UsePitchAct is true]`, Unit: "kg-m^2"},
	{Name: "PitchK", Type: Float, Desc: `Pitch actuator stiffness [used only when UsePitchAct is true]`, Unit: "kg-m^2/s^2"},
	{Name: "PitchC", Type: Float, Desc: `Pitch actuator damping [used only when UsePitchAct is true]`, Unit: "kg-m^2/s"},
	{Type: Header, Desc: `Outputs`},
	{Name: "SumPrint", Type: Bool, Desc: `Print summary data to "<RootName>.sum"`, Unit: "flag"},
	{Name: "OutFmt", Type: String, Desc: `Format used for text tabular output (except time)`, Unit: "quoted string"},
	{Name: "NNodeOuts", Type: Int, Desc: `Number of nodes to output to file [0 - 9]`},
	{Name: "OutNd", Type: Ints, NumVar: "NNodeOuts", Desc: `Nodes whose values will be output`},
	{Name: "OutList", Type: OutList, Desc: `The next line(s) contains a list of output parameters.  See OutListParameters.xlsx for a listing of available output channels`},
})
