package schema

var ElastoDynBlade = RegisterSchemas("ElastoDynBlade", []Schema{
	{Type: Header, Desc: "ElastoDynBlade Input File"},
	{Name: "Title", Type: Title},
	{Type: Header, Desc: "Blade Parameters"},
	{Name: "NBlInpSt", Type: Int, Desc: `Number of blade input stations`},
	{Name: "BldFlDmp(1)", Type: Float, Desc: `Blade flap mode #1 structural damping in percent of critical`, Unit: "%"},
	{Name: "BldFlDmp(2)", Type: Float, Desc: `Blade flap mode #2 structural damping in percent of critical`, Unit: "%"},
	{Name: "BldEdDmp(1)", Type: Float, Desc: `Blade edge mode #1 structural damping in percent of critical`, Unit: "%"},
	{Type: Header, Desc: `Blade Adjustment Factors`},
	{Name: "FlStTunr(1)", Type: Float, Desc: `Blade flapwise modal stiffness tuner, 1st mode`},
	{Name: "FlStTunr(2)", Type: Float, Desc: `Blade flapwise modal stiffness tuner, 2nd mode`},
	{Name: "AdjBlMs", Type: Float, Desc: `Factor to adjust blade mass density`},
	{Name: "AdjFlSt", Type: Float, Desc: `Factor to adjust blade flap stiffness`},
	{Name: "AdjEdSt", Type: Float, Desc: `Factor to adjust blade edge stiffness`},
	{Type: Header, Desc: `Distributed Blade Properties`},
	{Name: "BlInpSt", Type: Table, NumVar: "NBlInpSt", TableHeaderSize: 2, TableColumns: []Column{
		{Name: "BlFract", Type: Float, Unit: "-"},
		{Name: "PitchAxis", Type: Float, Unit: "-"},
		{Name: "StrcTwst", Type: Float, Unit: "deg"},
		{Name: "BMassDen", Type: Float, Unit: "kg/m"},
		{Name: "FlpStff", Type: Float, Unit: "Nm^2"},
		{Name: "EdgStff", Type: Float, Unit: "Nm^2"},
	}},
	{Type: Header, Desc: `Blade Mode Shapes`},
	{Name: "BldFl1Sh(2)", Type: Float, Desc: `Flap mode 1, coeff of x^2`},
	{Name: "BldFl1Sh(3)", Type: Float, Desc: `           , coeff of x^3`},
	{Name: "BldFl1Sh(4)", Type: Float, Desc: `           , coeff of x^4`},
	{Name: "BldFl1Sh(5)", Type: Float, Desc: `           , coeff of x^5`},
	{Name: "BldFl1Sh(6)", Type: Float, Desc: `           , coeff of x^6`},
	{Name: "BldFl2Sh(2)", Type: Float, Desc: `Flap mode 2, coeff of x^2`},
	{Name: "BldFl2Sh(3)", Type: Float, Desc: `           , coeff of x^3`},
	{Name: "BldFl2Sh(4)", Type: Float, Desc: `           , coeff of x^4`},
	{Name: "BldFl2Sh(5)", Type: Float, Desc: `           , coeff of x^5`},
	{Name: "BldFl2Sh(6)", Type: Float, Desc: `           , coeff of x^6`},
	{Name: "BldEdgSh(2)", Type: Float, Desc: `Edge mode 1, coeff of x^2`},
	{Name: "BldEdgSh(3)", Type: Float, Desc: `           , coeff of x^3`},
	{Name: "BldEdgSh(4)", Type: Float, Desc: `           , coeff of x^4`},
	{Name: "BldEdgSh(5)", Type: Float, Desc: `           , coeff of x^5`},
	{Name: "BldEdgSh(6)", Type: Float, Desc: `           , coeff of x^6`},
})
