package schema

var InflowWind = RegisterSchemas("InflowWind", []Schema{
	{Type: Header, Desc: "InflowWind Input File"},
	{Name: "Title", Type: Title},
	{Type: Header, Desc: "General"},
	{Name: "Echo", Type: Bool, Desc: `Echo input data to <RootName>.ech`, Unit: "flag"},
	{Name: "WindType", Type: Int, Desc: `switch for wind file type (1=steady; 2=uniform; 3=binary TurbSim FF; 4=binary Bladed-style FF; 5=HAWC format; 6=User defined; 7=native Bladed FF)`},
	{Name: "PropagationDir", Type: Float, Desc: `Direction of wind propagation (meteorological rotation from aligned with X (positive rotates towards -Y) -- degrees) (not used for native Bladed format WindType=7)`},
	{Name: "VFlowAng", Type: Float, Desc: `Upflow angle (degrees) (not used for native Bladed format WindType=7)`},
	{Name: "NWindVel", Type: Int, Desc: `Number of points to output the wind velocity    (0 to 9)`},
	{Name: "WindVxiList", Type: Floats, NumVar: "NWindVel", Desc: `List of coordinates in the inertial X direction (m)`},
	{Name: "WindVyiList", Type: Floats, NumVar: "NWindVel", Desc: `List of coordinates in the inertial Y direction (m)`},
	{Name: "WindVziList", Type: Floats, NumVar: "NWindVel", Desc: `List of coordinates in the inertial Z direction (m)`},
	{Type: Header, Desc: `Parameters for Steady Wind Conditions [used only for WindType = 1]`},
	{Name: "HWindSpeed", Type: Float, Desc: `Horizontal wind speed`, Unit: "m/s"},
	{Name: "RefHt", Type: Float, Desc: `Reference height for horizontal wind speed`, Unit: "m"},
	{Name: "PLExp", Type: Float, Desc: `Power law exponent`, Unit: "-"},
	{Type: Header, Desc: `Parameters for Uniform wind file   [used only for WindType = 2]`},
	{Name: "Filename_Uni", Type: File, FileType: "UniformWind", Desc: `Filename of time series data for uniform wind field`},
	{Name: "RefHt_Uni", Type: Float, Desc: `Reference height for horizontal wind speed`, Unit: "m"},
	{Name: "RefLength", Type: Float, Desc: `Reference length for linear horizontal and vertical sheer`},
	{Type: Header, Desc: `Parameters for Binary TurbSim Full-Field files   [used only for WindType = 3]`},
	{Name: "FileName_BTS", Type: Path, Desc: `Name of the Full field wind file to use (.bts)`},
	{Type: Header, Desc: `Parameters for Binary Bladed-style Full-Field files   [used only for WindType = 4 or WindType = 7]`},
	{Name: "FileNameRoot", Type: Path, Desc: `WindType=4: Rootname of the full-field wind file to use (.wnd, .sum); WindType=7: name of the intermediate file with wind scaling values`},
	{Name: "TowerFile", Type: Bool, Desc: `Have tower file (.twr) ignored when WindType = 7`, Unit: "flag"},
	{Type: Header, Desc: `Parameters for HAWC-format binary files  [Only used with WindType = 5]`},
	{Name: "FileName_u", Type: Path, Desc: `name of the file containing the u-component fluctuating wind (.bin)`},
	{Name: "FileName_v", Type: Path, Desc: `name of the file containing the v-component fluctuating wind (.bin)`},
	{Name: "FileName_w", Type: Path, Desc: `name of the file containing the w-component fluctuating wind (.bin)`},
	{Name: "nx", Type: Int, Desc: `number of grids in the x direction (in the 3 files above)`},
	{Name: "ny", Type: Int, Desc: `number of grids in the y direction (in the 3 files above)`},
	{Name: "nz", Type: Int, Desc: `number of grids in the z direction (in the 3 files above)`},
	{Name: "dx", Type: Int, Desc: `distance (in meters) between points in the x direction`, Unit: "m"},
	{Name: "dy", Type: Int, Desc: `distance (in meters) between points in the y direction`, Unit: "m"},
	{Name: "dz", Type: Int, Desc: `distance (in meters) between points in the z direction`, Unit: "m"},
	{Name: "RefHt_Hawc", Type: Float, Desc: `reference height; the height (in meters) of the vertical center of the grid`, Unit: "m"},
	{Type: Header, Desc: `Scaling parameters for turbulence`},
	{Name: "ScaleMethod", Type: Int, Desc: `Turbulence scaling method [0 = none, 1 = direct scaling, 2 = calculate scaling factor based on a desired standard deviation]`},
	{Name: "SFx", Type: Float, Desc: `Turbulence scaling factor for the x direction [ScaleMethod=1]`},
	{Name: "SFy", Type: Float, Desc: `Turbulence scaling factor for the y direction [ScaleMethod=1]`},
	{Name: "SFz", Type: Float, Desc: `Turbulence scaling factor for the z direction [ScaleMethod=1]`},
	{Name: "SigmaFx", Type: Float, Desc: `Turbulence standard deviation to calculate scaling from in x direction [ScaleMethod=2]`, Unit: "m/s"},
	{Name: "SigmaFy", Type: Float, Desc: `Turbulence standard deviation to calculate scaling from in y direction [ScaleMethod=2]`, Unit: "m/s"},
	{Name: "SigmaFz", Type: Float, Desc: `Turbulence standard deviation to calculate scaling from in z direction [ScaleMethod=2]`, Unit: "m/s"},
	{Type: Header, Desc: `Mean wind profile parameters (added to HAWC-format files)`},
	{Name: "URef", Type: Float, Desc: `Mean u-component wind speed at the reference height`, Unit: "m/s"},
	{Name: "WindProfile", Type: Int, Desc: `Wind profile type (0=constant;1=logarithmic,2=power law)`, Unit: "switch"},
	{Name: "PLExp_Hawc", Type: Float, Desc: `Power law exponent (used for PL wind profile type only)`},
	{Name: "Z0", Type: Float, Desc: `Surface roughness length (m) (used for LG wind profile type only)`, Unit: "m"},
	{Name: "XOffset", Type: Float, Desc: `Initial offset in +x direction (shift of wind box)`},
	{Type: Header, Desc: `OUTPUT`},
	{Name: "SumPrint", Type: Bool, Desc: `Print summary data to <RootName>.IfW.sum`, Unit: "flag"},
	{Name: "OutList", Type: OutList, Desc: `The next line(s) contains a list of output parameters.  See OutListParameters.xlsx for a listing of available output channels`},
})
