package schema

var ServoDyn = RegisterSchemas("ServoDyn", []Schema{
	{Type: Header, Desc: "ServoDyn Input File"},
	{Name: "Title", Type: Title},
	{Type: Header, Desc: "Simulation Control"},
	{Name: "Echo", Type: Bool, Desc: `Echo input data to "<rootname>.SD.ech"`, Unit: "flag"},
	{Name: "DT", Type: FloatDefault, Desc: `Communication interval for controllers (s) (or "default")`, Unit: "sec"},
	{Type: Header, Desc: `Pitch Control`},
	{Name: "PCMode", Type: Int, Desc: `Pitch control mode`, Unit: "switch", SwitchOptions: []Option{
		{0, "none"},
		{3, "user-defined from routine PitchCntrl"},
		{4, "user-defined from Simulink/Labview"},
		{5, "user-defined from Bladed-style DLL"},
	}},
	{Name: "TPCOn", Type: Float, Desc: `Time to enable active pitch control [unused when PCMode=0]`, Unit: "sec"},
	{Name: "TPitManS(1)", Type: Float, Desc: `Time to start override pitch maneuver for blade 1 and end standard pitch control`, Unit: "sec"},
	{Name: "TPitManS(2)", Type: Float, Desc: `Time to start override pitch maneuver for blade 2 and end standard pitch control`, Unit: "sec"},
	{Name: "TPitManS(3)", Type: Float, Desc: `Time to start override pitch maneuver for blade 3 and end standard pitch control [unused for 2 blades]`, Unit: "sec"},
	{Name: "PitManRat(1)", Type: Float, Desc: `Pitch rate at which override pitch maneuver heads toward final pitch angle for blade 1`, Unit: "deg/s"},
	{Name: "PitManRat(2)", Type: Float, Desc: `Pitch rate at which override pitch maneuver heads toward final pitch angle for blade 2`, Unit: "deg/s"},
	{Name: "PitManRat(3)", Type: Float, Desc: `Pitch rate at which override pitch maneuver heads toward final pitch angle for blade 3 [unused for 2 blades]`, Unit: "deg/s"},
	{Name: "BlPitchF(1)", Type: Float, Desc: `Blade 1 final pitch for pitch maneuvers`, Unit: "degrees"},
	{Name: "BlPitchF(2)", Type: Float, Desc: `Blade 2 final pitch for pitch maneuvers`, Unit: "degrees"},
	{Name: "BlPitchF(3)", Type: Float, Desc: `Blade 3 final pitch for pitch maneuvers [unused for 2 blades]`, Unit: "degrees"},
	{Type: Header, Desc: `Generator And Torque Control`},
	{Name: "VSContrl", Type: Int, Desc: `Variable-speed control mode`, Unit: "switch", SwitchOptions: []Option{
		{0, "none"},
		{1, "simple VS"},
		{3, "user-defined from routine UserVSCont"},
		{4, "user-defined from Simulink/Labview"},
		{5, "user-defined from Bladed-style DLL"},
	}},
	{Name: "GenModel", Type: Int, Desc: `Generator model [used only when VSContrl=0]`, Unit: "switch", SwitchOptions: []Option{
		{1, "simple"},
		{2, "Thevenin"},
		{3, "user-defined from routine UserGen"},
	}},
	{Name: "GenEff", Type: Float, Desc: `Generator efficiency [ignored by the Thevenin and user-defined generator models]`, Unit: "%"},
	{Name: "GenTiStr", Type: Bool, Desc: `Method to start the generator {T: timed using TimGenOn, F: generator speed using SpdGenOn}`, Unit: "flag"},
	{Name: "GenTiStp", Type: Bool, Desc: `Method to stop the generator {T: timed using TimGenOf, F: when generator power = 0}`, Unit: "flag"},
	{Name: "SpdGenOn", Type: Float, Desc: `Generator speed to turn on the generator for a startup (HSS speed) [used only when GenTiStr=False]`, Unit: "rpm"},
	{Name: "TimGenOn", Type: Float, Desc: `Time to turn on the generator for a startup (s) [used only when GenTiStr=True]`},
	{Name: "TimGenOf", Type: Float, Desc: `Time to turn off the generator (s) [used only when GenTiStp=True]`},
	{Type: Header, Desc: `Simple Variable-Speed Torque Control`},
	{Name: "VS_RtGnSp", Type: Float, Desc: `Rated generator speed for simple variable-speed generator control (HSS side) [used only when VSContrl=1]`, Unit: "rpm"},
	{Name: "VS_RtTq", Type: Float, Desc: `Rated generator torque/constant generator torque in Region 3 for simple variable-speed generator control (HSS side) [used only when VSContrl=1]`, Unit: "N-m"},
	{Name: "VS_Rgn2K", Type: Float, Desc: `Generator torque constant in Region 2 for simple variable-speed generator control (HSS side)  [used only when VSContrl=1]`, Unit: "N-m/rpm^2"},
	{Name: "VS_SlPc", Type: Float, Desc: `Rated generator slip percentage in Region 2 1/2 for simple variable-speed generator control [used only when VSContrl=1]`, Unit: "%"},
	{Type: Header, Desc: `Simple Induction Generator`},
	{Name: "SIG_SlPc", Type: Float, Desc: `Rated generator slip percentage [used only when VSContrl=0 and GenModel=1]`, Unit: "%"},
	{Name: "SIG_SySp", Type: Float, Desc: `Synchronous (zero-torque) generator speed [used only when VSContrl=0 and GenModel=1]`, Unit: "rpm"},
	{Name: "SIG_RtTq", Type: Float, Desc: `Rated torque [used only when VSContrl=0 and GenModel=1]`, Unit: "N-m"},
	{Name: "SIG_PORt", Type: Float, Desc: `Pull-out ratio [used only when VSContrl=0 and GenModel=1]`, Unit: "Tpullout/Trated"},
	{Type: Header, Desc: `Thevenin-Equivalent Induction Generator`},
	{Name: "TEC_Freq", Type: Float, Desc: `Line frequency [50 or 60] [used only when VSContrl=0 and GenModel=2]`, Unit: "Hz"},
	{Name: "TEC_NPol", Type: Float, Desc: `Number of poles [even integer > 0] [used only when VSContrl=0 and GenModel=2]`},
	{Name: "TEC_SRes", Type: Float, Desc: `Stator resistance [used only when VSContrl=0 and GenModel=2]`, Unit: "ohms"},
	{Name: "TEC_RRes", Type: Float, Desc: `Rotor resistance [used only when VSContrl=0 and GenModel=2]`, Unit: "ohms"},
	{Name: "TEC_VLL", Type: Float, Desc: `Line-to-line RMS voltage (volts) [used only when VSContrl=0 and GenModel=2]`},
	{Name: "TEC_SLR", Type: Float, Desc: `Stator leakage reactance [used only when VSContrl=0 and GenModel=2]`, Unit: "ohms"},
	{Name: "TEC_RLR", Type: Float, Desc: `Rotor leakage reactance [used only when VSContrl=0 and GenModel=2]`, Unit: "ohms"},
	{Name: "TEC_MR", Type: Float, Desc: `Magnetizing reactance [used only when VSContrl=0 and GenModel=2]`, Unit: "ohms"},
	{Type: Header, Desc: `High-Speed Shaft Brake`},
	{Name: "HSSBrMode", Type: Int, Desc: `HSS brake model`, Unit: "switch", SwitchOptions: []Option{
		{0, "none"},
		{1, "simple"},
		{3, "user-defined from routine UserHSSBr"},
		{4, "user-defined from Simulink/Labview"},
		{5, "user-defined from Bladed-style DLL"},
	}},
	{Name: "THSSBrDp", Type: Float, Desc: `Time to initiate deployment of the HSS brake`, Unit: "sec"},
	{Name: "HSSBrDT", Type: Float, Desc: `Time for HSS-brake to reach full deployment once initiated (sec) [used only when HSSBrMode=1]`},
	{Name: "HSSBrTqF", Type: Float, Desc: `Fully deployed HSS-brake torque`, Unit: "N-m"},
	{Type: Header, Desc: `Nacelle-Yaw Control`},
	{Name: "YCMode", Type: Int, Desc: `Yaw control mode {0: none, 3: user-defined from routine UserYawCont, 4: user-defined from Simulink/Labview, 5: user-defined from Bladed-style DLL} (switch)`},
	{Name: "TYCOn", Type: Float, Desc: `Time to enable active yaw control [unused when YCMode=0]`, Unit: "sec"},
	{Name: "YawNeut", Type: Float, Desc: `Neutral yaw position--yaw spring force is zero at this yaw`, Unit: "degrees"},
	{Name: "YawSpr", Type: Float, Desc: `Nacelle-yaw spring constant`, Unit: "N-m/rad"},
	{Name: "YawDamp", Type: Float, Desc: `Nacelle-yaw damping constant`, Unit: "N-m/(rad/s)"},
	{Name: "TYawManS", Type: Float, Desc: `Time to start override yaw maneuver and end standard yaw control`, Unit: "sec"},
	{Name: "YawManRat", Type: Float, Desc: `Yaw maneuver rate (in absolute value)`, Unit: "deg/s"},
	{Name: "NacYawF", Type: Float, Desc: `Final yaw angle for override yaw maneuvers`, Unit: "degrees"},
	{Type: Header, Desc: `Aerodynamic Flow Control`},
	{Name: "AfCmode", Type: Int, Desc: `Airfoil control mode`, Unit: "switch", SwitchOptions: []Option{
		{0, "none"},
		{1, "cosine wave cycle"},
		{4, "user-defined from Simulink/Labview"},
		{5, "user-defined from Bladed-style DLL"},
	}},
	{Name: "AfC_Mean", Type: Float, Desc: `Mean level for cosine cycling or steady value [used only with AfCmode==1]`},
	{Name: "AfC_Amp", Type: Float, Desc: `Amplitude for for cosine cycling of flap signal [used only with AfCmode==1]`},
	{Name: "AfC_Phase", Type: Float, Desc: `Phase relative to the blade azimuth (0 is vertical) for for cosine cycling of flap signal [used only with AfCmode==1]`, Unit: "deg"},
	{Type: Header, Desc: `Structural Control`},
	{Name: "NumBStC", Type: Int, Desc: `Number of blade structural controllers (integer)`},
	{Name: "BStCfiles", Type: Paths, NumVar: "NumBStC", Desc: `Name of the files for blade structural controllers [unused when NumBStC==0]`, Unit: "quoted strings"},
	{Name: "NumNStC", Type: Int, Desc: `Number of nacelle structural controllers (integer)`},
	{Name: "NStCfiles", Type: Paths, NumVar: "NumNStC", Desc: `Name of the files for nacelle structural controllers [unused when NumNStC==0]`, Unit: "quoted strings"},
	{Name: "NumTStC", Type: Int, Desc: `Number of tower structural controllers (integer)`},
	{Name: "TStCfiles", Type: Paths, NumVar: "NumTStC", Desc: `Name of the files for tower structural controllers [unused when NumTStC==0]`, Unit: "quoted strings"},
	{Name: "NumSStC", Type: Int, Desc: `Number of substructure structural controllers (integer)`},
	{Name: "SStCfiles", Type: Paths, NumVar: "NumSStC", Desc: `Name of the files for substructure structural controllers [unused when NumSStC==0]`, Unit: "quoted strings"},
	{Type: Header, Desc: `Cable Control`},
	{Name: "CCmode", Type: Int, Desc: `Cable control mode {0: none, 4: user-defined from Simulink/Labview, 5: user-defined from Bladed-style DLL}`, Unit: "switch"},
	{Type: Header, Desc: `BLADED INTERFACE [used only with Bladed Interface]`},
	{Name: "DLL_FileName", Type: Path, Desc: `Name/location of the dynamic library {.dll [Windows] or .so [Linux]} in the Bladed-DLL format [used only with Bladed Interface]`},
	{Name: "DLL_InFile", Type: Path, Desc: `Name of input file sent to the DLL [used only with Bladed Interface]`},
	{Name: "DLL_ProcName", Type: String, Desc: `Name of procedure in DLL to be called [case sensitive; used only with DLL Interface]`},
	{Name: "DLL_DT", Type: FloatDefault, Desc: `Communication interval for dynamic library (or "default") [used only with Bladed Interface]`, Unit: "sec"},
	{Name: "DLL_Ramp", Type: Bool, Desc: `Whether a linear ramp should be used between DLL_DT time steps [introduces time shift when true] (flag) [used only with Bladed Interface]`},
	{Name: "BPCutoff", Type: Float, Desc: `Cutoff frequency for low-pass filter on blade pitch from DLL (Hz) [used only with Bladed Interface]`},
	{Name: "NacYaw_North", Type: Float, Desc: `Reference yaw angle of the nacelle when the upwind end points due North [used only with Bladed Interface]`, Unit: "deg"},
	{Name: "Ptch_Cntrl", Type: Float, Desc: `Record 28: Use individual pitch control {0: collective pitch; 1: individual pitch control} (switch) [used only with Bladed Interface]`},
	{Name: "Ptch_SetPnt", Type: Float, Desc: `Record  5: Below-rated pitch angle set-point [used only with Bladed Interface]`, Unit: "deg"},
	{Name: "Ptch_Min", Type: Float, Desc: `Record  6: Minimum pitch angle [used only with Bladed Interface]`, Unit: "deg"},
	{Name: "Ptch_Max", Type: Float, Desc: `Record  7: Maximum pitch angle [used only with Bladed Interface]`, Unit: "deg"},
	{Name: "PtchRate_Min", Type: Float, Desc: `Record  8: Minimum pitch rate (most negative value allowed) [used only with Bladed Interface]`, Unit: "deg/s"},
	{Name: "PtchRate_Max", Type: Float, Desc: `Record  9: Maximum pitch rate  [used only with Bladed Interface]`, Unit: "deg/s"},
	{Name: "Gain_OM", Type: Float, Desc: `Record 16: Optimal mode gain [used only with Bladed Interface]`, Unit: "Nm/(rad/s)^2"},
	{Name: "GenSpd_MinOM", Type: Float, Desc: `Record 17: Minimum generator speed [used only with Bladed Interface]`, Unit: "rpm"},
	{Name: "GenSpd_MaxOM", Type: Float, Desc: `Record 18: Optimal mode maximum speed [used only with Bladed Interface]`, Unit: "rpm"},
	{Name: "GenSpd_Dem", Type: Float, Desc: `Record 19: Demanded generator speed above rated [used only with Bladed Interface]`, Unit: "rpm"},
	{Name: "GenTrq_Dem", Type: Float, Desc: `Record 22: Demanded generator torque above rated [used only with Bladed Interface]`, Unit: "Nm"},
	{Name: "GenPwr_Dem", Type: Float, Desc: `Record 13: Demanded power [used only with Bladed Interface]`, Unit: "W"},
	{Type: Header, Desc: `Bladed Interface Torque-Speed Look-Up Table`},
	{Name: "DLL_NumTrq", Type: Int, Desc: `Record 26: No. of points in torque-speed look-up table {0 = none and use the optimal mode parameters; nonzero = ignore the optimal mode PARAMETERs by setting Record 16 to 0.0} [used only with Bladed Interface]`},
	{Name: "GenSpdTrq", Type: Table, NumVar: "DLL_NumTrq", TableHeaderSize: 2, TableColumns: []Column{
		{Name: "GenSpd_TLU", Type: Float, Unit: "rpm"},
		{Name: "GenTrq_TLU", Type: Float, Unit: "Nm"},
	}},
	{Type: Header, Desc: `Output`},
	{Name: "SumPrint", Type: Bool, Desc: `Print summary data to <RootName>.sum (flag) (currently unused)`},
	{Name: "OutFile", Type: Int, Desc: `Switch to determine where output will be placed: {1: in module output file only; 2: in glue code output file only; 3: both} (currently unused)`},
	{Name: "TabDelim", Type: Bool, Desc: `Use tab delimiters in text tabular output file? (flag) (currently unused)`},
	{Name: "OutFmt", Type: String, Desc: `Format used for text tabular output (except time).  Resulting field should be 10 characters. (quoted string) (currently unused)`},
	{Name: "TStart", Type: Float, Desc: `Time to begin tabular output (s) (currently unused)`},
	{Name: "OutList", Type: OutList, Desc: `The next line(s) contains a list of output parameters.  See OutListParameters.xlsx for a listing of available output channels, (-)`},
})
