// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAnalysisCase() {
  return window['go']['main']['App']['AddAnalysisCase']();
}

export function CancelEvaluate() {
  return window['go']['main']['App']['CancelEvaluate']();
}

export function EvaluateLinearization(arg1, arg2) {
  return window['go']['main']['App']['EvaluateLinearization'](arg1, arg2);
}

export function ImportModelDialog() {
  return window['go']['main']['App']['ImportModelDialog']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function RemoveAnalysisCase(arg1) {
  return window['go']['main']['App']['RemoveAnalysisCase'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveProjectDialog() {
  return window['go']['main']['App']['SaveProjectDialog']();
}

export function SelectExec() {
  return window['go']['main']['App']['SelectExec']();
}

export function UpdateAnalysis(arg1) {
  return window['go']['main']['App']['UpdateAnalysis'](arg1);
}

export function UpdateModel(arg1) {
  return window['go']['main']['App']['UpdateModel'](arg1);
}
