// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAnalysisCase() {
  return window['go']['main']['App']['AddAnalysisCase']();
}

export function CancelEvaluate() {
  return window['go']['main']['App']['CancelEvaluate']();
}

export function EvaluateCase(arg1) {
  return window['go']['main']['App']['EvaluateCase'](arg1);
}

export function FetchAnalysis() {
  return window['go']['main']['App']['FetchAnalysis']();
}

export function FetchEvaluate() {
  return window['go']['main']['App']['FetchEvaluate']();
}

export function FetchModel() {
  return window['go']['main']['App']['FetchModel']();
}

export function FetchResults() {
  return window['go']['main']['App']['FetchResults']();
}

export function GenerateDiagram(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateDiagram'](arg1, arg2, arg3);
}

export function GetEvaluateLog(arg1) {
  return window['go']['main']['App']['GetEvaluateLog'](arg1);
}

export function GetModeViz(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetModeViz'](arg1, arg2, arg3);
}

export function ImportModelDialog() {
  return window['go']['main']['App']['ImportModelDialog']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenCaseDirDialog() {
  return window['go']['main']['App']['OpenCaseDirDialog']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function RemoveAnalysisCase(arg1) {
  return window['go']['main']['App']['RemoveAnalysisCase'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveProjectDialog() {
  return window['go']['main']['App']['SaveProjectDialog']();
}

export function SelectExec() {
  return window['go']['main']['App']['SelectExec']();
}

export function UpdateAnalysis(arg1) {
  return window['go']['main']['App']['UpdateAnalysis'](arg1);
}

export function UpdateEvaluate(arg1) {
  return window['go']['main']['App']['UpdateEvaluate'](arg1);
}

export function UpdateModel(arg1) {
  return window['go']['main']['App']['UpdateModel'](arg1);
}
