// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ImportModelDialog():Promise<main.Project>;

export function LoadConfig():Promise<main.Config>;

export function OpenProject(arg1:string):Promise<main.Project>;

export function OpenProjectDialog():Promise<main.Project>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SaveProject(arg1:string):Promise<main.Project>;

export function SaveProjectDialog():Promise<main.Project>;

export function SelectExec():Promise<main.Project>;

export function UpdateModel(arg1:main.Model):Promise<main.Project>;
