// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create() {
  return window['go']['main']['Project']['Create']();
}

export function Open() {
  return window['go']['main']['Project']['Open']();
}

export function Save() {
  return window['go']['main']['Project']['Save']();
}

export function SelectExec() {
  return window['go']['main']['Project']['SelectExec']();
}
