// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create():Promise<any>;

export function Open():Promise<any>;

export function Save():Promise<void>;

export function SelectExec():Promise<string>;
