name: Wails build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: ACDC, platform: linux/amd64, os: ubuntu-latest},
          # {name: ACDC, platform: linux/arm64, os: ubuntu-latest},
          {name: ACDC, platform: windows/amd64, os: windows-latest},
          {name: ACDC, platform: darwin/amd64, os: macos-latest},
          {name: ACDC, platform: darwin/arm64, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: 1.21